### ISSUE TITLE
net-listen.py not working

### ISSUE THREAD

**Issue by souhaiebtar** [KalleHallden/reddit_automations#4]
first thank you,

i created a `settings.ini` file
```
[settings]
IP_NETWORK=192.168.1.1
IP_DEVICE=192.168.1.13
```

IP_NETWORK contain the ip of my router
and IP_DEVICE the ips of the device i want to check

i'm running macos,

when i run your script nothing work, 
would please help

**Comment by kartikeytewari** [comment]
Make a .env file with this data:
IP_NETWORK=192.168.1.1
IP_DEVICE=192.168.1.13

Also, remove the settings.ini file. Then run the script, it should work afaik.

**Comment by souhaiebtar** [comment]
@kartikeytewari  i also did that before creating this issue but it didn't work either

**Comment by kartikeytewari** [comment]
I just observed, that the IP is filtered in a weird manner, the connected ip gets appended by a ":"
So, make the .env file as this
IP_NETWORK=192.168.1.1
IP_DEVICE=192.168.1.13:

**Comment by kartikeytewari** [comment]
Also, if you are connected to a Class-C network (most likely if you are using mobile hotspot or Wi-Fi) then, IP_NETWORK would be 192.168.1.255 not 192.168.1.1

**Comment by souhaiebtar** [comment]
@kartikeytewari thanks men, really helpful
